version: '3'

services:
  backend:
    image: bhub-backend
    build:
      context: ./bhub_project
      dockerfile: ./Dockerfile
    ports:
      - 1024:1024
    depends_on:
      - mongodb
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: bosco
      ME_CONFIG_BASICAUTH_PASSWORD: MongoExpress2019!
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: MongoDB2019!
      ME_CONFIG_MONGODB_SERVER: mongodb
    links:
      - mongodb
    networks:
      - mongo-compose-network
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoDB2019!
      MONGO_INITDB_DATABASE: bhub_project
    ports:
      - "27017:27017"
    volumes:
      - ../Docker/Volumes/MongoDB:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:rw 
    networks:
      - mongo-compose-network

networks: 
    mongo-compose-network:
      driver: bridge