# Generated by Django 4.1.5 on 2023-01-19 15:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unica ID para este cliente', primary_key=True, serialize=False)),
                ('razao_social', models.CharField(choices=[('CPF', 'Pessoa fisica'), ('CNPJ', 'Pessoa juridica')], max_length=4)),
                ('telefone', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=100)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('faturamento_declarado', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='DadosBancarios',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Unica ID para esta conta bancaria', primary_key=True, serialize=False)),
                ('agencia', models.PositiveSmallIntegerField()),
                ('conta', models.PositiveSmallIntegerField()),
                ('banco', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.cliente')),
            ],
        ),
    ]
